version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: library-mysql
    environment:
      MYSQL_ROOT_PASSWORD: libpass
      MYSQL_DATABASE: library
      MYSQL_USER: libraryuser
      MYSQL_PASSWORD: libpass
    volumes:
      - mysql-data:/var/lib/mysql
      - ./ProjectLibrary2/library.sql:/docker-entrypoint-initdb.d/library.sql:ro
    networks:
      - library-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "-plibpass"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  app:
    build:
      context: ./ProjectLibrary2
      dockerfile: Dockerfile
    container_name: library-app
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/library
      SPRING_DATASOURCE_USERNAME: libraryuser
      SPRING_DATASOURCE_PASSWORD: libpass
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - library-network
    restart: unless-stopped

networks:
  library-network:
    driver: bridge

volumes:
  mysql-data:
