version: "3.8"

services:
  mysql:
    image: mysql:8.0
    container_name: library-mysql
    environment:
      MYSQL_ROOT_PASSWORD: libpass
      MYSQL_DATABASE: library
      MYSQL_USER: libraryuser
      MYSQL_PASSWORD: libpass
    volumes:
      - mysql_data:/var/lib/mysql
      - ./library.sql:/docker-entrypoint-initdb.d/library.sql
    ports:
      - "3306:3306"

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: library-app
    depends_on:
      - mysql
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/library
      SPRING_DATASOURCE_USERNAME: libraryuser
      SPRING_DATASOURCE_PASSWORD: libpass
      SERVER_PORT: 8080
    ports:
      - "8080:8080"
    restart: always

volumes:
  mysql_data:
