apiVersion: apps/v1
kind: Deployment
metadata:
  name: library-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: library-app
  template:
    metadata:
      labels:
        app: library-app
    spec:
      containers:
      - name: library-app
        image: geodude132/projectlibrary2-app:latest
        ports:
        - containerPort: 8080
        env:
        - name: SPRING_DATASOURCE_URL
          value: jdbc:mysql://mysql:3306/library
        - name: SPRING_DATASOURCE_USERNAME
          value: libuser
        - name: SPRING_DATASOURCE_PASSWORD
          value: libpass
