apiVersion: v1
kind: Service
metadata:
  name: library-service
spec:
  selector:
    app: library-app
  type: NodePort
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30080
