apiVersion: apps/v1
kind: Deployment
metadata:
  name: library-app
  labels:
    app: library-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: library-app
  template:
    metadata:
      labels:
        app: library-app
    spec:
      initContainers:
      - name: wait-for-mysql
        image: busybox:1.35
        command:
          - sh
          - -c
          - |
            until nc -z mysql 3306; do
              echo "waiting for mysql..."
              sleep 5
            done
      containers:
      - name: library-app
        image: geodude132/projectlibrary2-app:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
          name: http
        env:
        - name: SPRING_DATASOURCE_URL
          value: jdbc:mysql://mysql:3306/library
        - name: SPRING_DATASOURCE_USERNAME
          value: libuser
        - name: SPRING_DATASOURCE_PASSWORD
          value: libpass
        - name: SERVER_PORT
          value: "8080"
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 60
          periodSeconds: 10
          timeoutSeconds: 5
        readinessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 5
          timeoutSeconds: 5

---
apiVersion: v1
kind: Service
metadata:
  name: library-service
  labels:
    app: library-app
spec:
  type: NodePort
  selector:
    app: library-app
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
    nodePort: 30500
